version: '3.8'

services:
  app:
    build: .
    container_name: BioPure
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
      SPRING_DATASOURCE_USERNAME: rm555018
      SPRING_DATASOURCE_PASSWORD: 210505
    networks:
      - app-network

networks:
  app-network:
