CREATE SEQUENCE RM555018.PRODUTO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE RM555018.TBL_PRODUTO (
    ID INTEGER DEFAULT RM555018.PRODUTO_SEQ.NEXTVAL NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL
);
