name: CI/CD BioPure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Maven
        # Build sem rodar testes
        run: mvn clean install -DskipTests

      - name: Run Tests (H2 Profile)
        # Rodar testes usando profile test para H2
        run: mvn test -Ptest

  docker:
    name: Build & Push Docker
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build da imagem Docker
        run: |
          docker build -t juhdias/biopure:latest .

      - name: Push da imagem para Docker Hub
        run: |
          docker push juhdias/biopure:latest